# Generated by Django 3.0.2 on 2020-02-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20200227_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='due_date',
        ),
    ]
